name: Nightly Push

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8 am UTC / 1 am PDT / 4 am EDT
  workflow_dispatch:

jobs:
  deploy-nightly:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # config GIT so it can do git push
      - uses: fregante/setup-git-user@v1

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: yarn

      - name: Activate Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          corepack yarn --version

      - run: corepack yarn install --immutable
      - run: corepack yarn deploy-nightly
