name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ["24"]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Activate Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          corepack yarn --version

      - name: Install recoil-devtools dependencies
        run: |
          cd packages-ext/recoil-devtools
          corepack yarn install --immutable

      - name: Install dependencies
        run: corepack yarn install --immutable

      - run: corepack yarn flow
      - run: corepack yarn test:typescript
      - run: corepack yarn test
      - run: corepack yarn lint
      - run: corepack yarn build
      - run: corepack yarn pack

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: build/recoil/*.tgz
